### ISSUE TITLE
JSON output

### ISSUE THREAD

**Issue by rmfarrell** [static-dev/spike-rooftop#14]
Could we add the option for this to output the response as `.json`?

**Comment by jescalan** [comment]
Hmm, yeah we could, but what is the advantage of this over just hitting rooftop's API directly?

**Comment by kylemac** [comment]
@jescalan we have a use-case where we don't want to hit their hosted API too often, because the data rarely changes. So we'd rather write our own json file and push it to a CDN.

**Comment by jescalan** [comment]
👍 Seems legit. Want me to add this feature, or do you and/or ryan want to take it?

**Comment by kylemac** [comment]
@jescalan - @rmfarrell has a patch solution at the project level. I'd like for you to put this on your list and  fix at the library level please.

**Comment by jescalan** [comment]
Will do 🌵
