### ISSUE TITLE
Use spike-util by default

### ISSUE THREAD

**Issue by hhsnopek** [static-dev/spike-rooftop#26]
`const f = Util.filePathFromLoader(ctx).absolute`
If we require this for spike-rooftop to work with posthtml we should load it for the user, rather than having the user add it into their `app.js`

**Comment by jescalan** [comment]
Ah thats actually not necessary, you can just use `ctx.resourcePath` instead

**Comment by hhsnopek** [comment]
cc @michaelcd - I was using that before, but posthtml was having a fuss about it

**Comment by michaelcd** [comment]
I was looking at this earlier today. Using `ctx.resourcePath` works for normal view files, however it won't work for the `writeTemplate` function. I'll look into this and update the function fix this.
