### ISSUE TITLE
`per_page` option stopped working after version 0.5.0

### ISSUE THREAD

**Issue by michaelcd** [static-dev/spike-rooftop#57]
It appears as though adding a `per_page` option in a `contentTypes` object stopped working in version `0.7.0`, so that queries will still return the default number of posts (10). This may be related to a change in rooftop-client `1.0.0`. I'm still investigating, will update once I have more information.

**Comment by hhsnopek** [comment]
Could you add spike & reshape versions here?

**Comment by michaelcd** [comment]
I reproduced this error in rooftop-client, so it's actually not spike-rooftop. Going to move my issue over there.
