### ISSUE TITLE
Can spike-rooftop be used in sugarfree mode?

### ISSUE THREAD

**Issue by jalbstmeijer** [static-dev/spike-rooftop#90]
I'm trying to use spike-rooftop in sugarfree mode, to allow me to use a plain html template.

my app.js looks like:
`
const htmlStandards = require('reshape-standard')
const cssStandards = require('spike-css-standards')
const jsStandards = require('babel-preset-env')
const dynamicImport = require('babel-plugin-syntax-dynamic-import')
const pageId = require('spike-page-id')
const Rooftop = require('spike-rooftop')
const locals = { foo: 'bar' }

module.exports = {
  devtool: 'source-map',
  matchers: {
    html: '*(**/)*.sgr',
    css: '*(**/)*.sss'
  },
  ignore: ['**/layout.sgr', '**/_*', '**/.*', 'readme.md', 'yarn.lock'],
  reshape: htmlStandards({
    parser: false,
    locals
  }),
  postcss: cssStandards(),
  babel: { presets: [[jsStandards, { modules: false }]], plugins: [dynamicImport] },
  plugins: [
    new Rooftop({ addDataTo: locals, name: 'test', url: 'XXX', apiToken: 'XXX', contentTypes: [{ name: 'posts', template: {path: 'templates/post.html',output: (post) => { return `posts/${post.slug}.html` }}}] })
  ]

}
`

mysql views/index.sgr looks like:
`
extends(src='layout.sgr')
  block(name='content')

    each(loop='post of rooftop.posts')
      li {{ JSON.stringify(post) }}

    p foo: {{ foo }}
`

with "parser: false" I get: (foo var gets interpreted, loop not)

`
extends(src='layout.sgr')
  block(name='content')

    each(loop='post of rooftop.posts')
      li undefined

    p foo: bar
`
without a disabled parser I get the posts too in the output.
I'm I missing something? is this expected behavior?

Is it possible to have plain html templates including loops like this to be interpreted?

Gr, J

**Comment by jalbstmeijer** [comment]
I, see;

   <each loop="post of rooftop.posts">
      <p>{{ JSON.stringify(post) }}</p>
   </each>

needs to be the syntax

**Comment by jescalan** [comment]
Haha yep, I think what happened here was that you de-activated the whitespace parser, then continued to use the whitespace syntax. As long as you change over to normal html syntax as seen in your second comment, you should be fine.

There is a "sugarfree" template here that demonstrates a full example of how the syntax should look 😁 

https://github.com/static-dev/spike-tpl-sugarfree
