### ISSUE TITLE
Debugging error

### ISSUE THREAD

**Issue by jalbstmeijer** [static-dev/spike-rooftop#96]
Hi,

Moving this issue from the spike repo, https://github.com/static-dev/spike/issues/73
I'm getting the following error with random id's when compiling;

spike compile

✗ ERROR
{ [Error] id: '25067473' }

I'm running spike-2.0.0 and spike-rooftop-1.0.0

The last suggestion was to provide a trace.
How do I collect such trace?

Gr, J

**Comment by jalbstmeijer** [comment]
Update: A fix was introduced showing a human readable error. In my case an API end point error.

**Comment by jescalan** [comment]
Glad this was worked out, and I'm so sorry for the error!
